/**
 * The feishu-bot storage domain: four tables over `ctx.storageDomain`
 * (design §5). Records are validated by zod at the domain boundary;
 * ids crossing the Feishu wire are branded.
 *
 * Text privacy rule: `text` exists only while an inbound message record is in
 * `received`/`recovering`; the write that moves it to a terminal state clears
 * it in the same durable step.
 */
import { defineDomain, domainTable } from '@deepseek-ai/dsh-storage-domain'
import type { Branded } from '@deepseek-ai/dsh-brand'
import { z } from 'zod'

/** Feishu chat id (`oc_…`). */
export type FeishuChatId = Branded<'FeishuChatId'>
/** Feishu message id (`om_…`). */
export type FeishuMessageId = Branded<'FeishuMessageId'>
/** Feishu user open id (`ou_…`), scoped to this app. */
export type FeishuOpenId = Branded<'FeishuOpenId'>
/** Feishu event id — the inbound idempotency key. */
export type FeishuEventId = Branded<'FeishuEventId'>
/** Session id string as used by the harness (kept opaque here). */
export type SessionIdString = Branded<'SessionIdString'>
/** DSH user-message id generated by createUserMessage (reconciliation key). */
export type DshMessageId = Branded<'DshMessageId'>
/** Deterministic outbound segment key `chatId:sessionId:sourceEventSeq:segmentIndex`. */
export type OutboundSegmentId = Branded<'OutboundSegmentId'>
/** Bridge-owned pending approval card key. */
export type PendingCardId = Branded<'PendingCardId'>

const brandedString = <T extends string>() => z.string().min(1) as unknown as z.ZodType<Branded<T>>

/** One chat↔session binding; at most one active per chat. */
export const chatBinding = z.object({
  sessionId: brandedString<'SessionIdString'>(),
  /** `active` = live binding; `unavailable` = restart found the session unusable. */
  status: z.enum(['active', 'unavailable']),
  boundBy: brandedString<'FeishuOpenId'>(),
  boundAt: z.number().int().nonnegative(),
})
export type ChatBinding = z.infer<typeof chatBinding>

/** Inbound message-event lifecycle (design §6.1). */
export const inboundMessage = z.object({
  kind: z.literal('message'),
  chatId: brandedString<'FeishuChatId'>(),
  senderOpenId: brandedString<'FeishuOpenId'>(),
  receivedAt: z.number().int().nonnegative(),
  /**
   * received: durable, not yet routed; recovering: restart scan re-owns it.
   * enqueued/rejected/expired are terminal; the transition write clears text.
   */
  status: z.enum(['received', 'recovering', 'enqueued', 'rejected', 'expired']),
  /** Present only in received/recovering (text privacy rule). */
  text: z.string().optional(),
  /** Target session captured at routing time. */
  target: brandedString<'SessionIdString'>().optional(),
  /** DSH message id minted before followup — the reconciliation key. */
  messageId: brandedString<'DshMessageId'>().optional(),
  /** Rejection/expiry reason code for the terminal reply. */
  reason: z.string().optional(),
})

/** Inbound command-event lifecycle (design §6.2; no `recovering` state). */
export const inboundCommand = z.object({
  kind: z.literal('command'),
  chatId: brandedString<'FeishuChatId'>(),
  senderOpenId: brandedString<'FeishuOpenId'>(),
  receivedAt: z.number().int().nonnegative(),
  /** received → committed | rejected | expired; interrupted recovery reads received + target. */
  status: z.enum(['received', 'committed', 'rejected', 'expired']),
  command: z.string(),
  /** Hash of normalized args — audit without storing free text. */
  commandArgsHash: z.string(),
  /** Session the command acted on, written before the side effect commits. */
  target: brandedString<'SessionIdString'>().optional(),
  /** Stored outcome text for idempotent re-delivery of committed commands. */
  result: z.string().optional(),
})

export const inboundEvent = z.discriminatedUnion('kind', [inboundMessage, inboundCommand])
export type InboundEvent = z.infer<typeof inboundEvent>
export type InboundMessage = z.infer<typeof inboundMessage>
export type InboundCommand = z.infer<typeof inboundCommand>

/** Pending approval card (design §6.4); deleted on decision or restart sweep. */
export const pendingCard = z.object({
  kind: z.literal('approval'),
  pendingId: z.string().min(1),
  chatId: brandedString<'FeishuChatId'>(),
  /** Backfilled after send; absent = crashed before exposure, sweep deletes. */
  cardMessageId: brandedString<'FeishuMessageId'>().optional(),
  createdAt: z.number().int().nonnegative(),
})
export type PendingCard = z.infer<typeof pendingCard>

/** One outbound text segment; key is the deterministic four-tuple (design §6.3). */
export const outboundSegment = z.object({
  chatId: brandedString<'FeishuChatId'>(),
  sessionId: brandedString<'SessionIdString'>(),
  /** Source session event seq the projection derived this segment from. */
  sourceEventSeq: z.number().int().nonnegative(),
  segmentIndex: z.number().int().nonnegative(),
  segmentCount: z.number().int().positive(),
  text: z.string(),
  status: z.enum(['pending', 'sent', 'abandoned']),
  createdAt: z.number().int().nonnegative(),
})
export type OutboundSegment = z.infer<typeof outboundSegment>

/** Per-chat projection watermark: events at or below need no re-projection. */
export const feishuBotGlobal = z.object({
  /** chatId → last projected source event seq per bound session. */
  watermarks: z.record(z.string(), z.number().int().nonnegative()),
})
export type FeishuBotGlobal = z.infer<typeof feishuBotGlobal>

/** The feishu-bot domain: identity, version, and all four tables. */
export const feishuBotDomain = defineDomain({
  name: 'feishu-bot',
  version: 1,
  global: {
    schema: feishuBotGlobal,
    initial: { watermarks: {} },
  },
  tables: {
    bindings: domainTable<FeishuChatId, ChatBinding>(chatBinding),
    inboundEvents: domainTable<FeishuEventId, InboundEvent>(inboundEvent),
    pendingCards: domainTable<PendingCardId, PendingCard>(pendingCard),
    outboundSegments: domainTable<OutboundSegmentId, OutboundSegment>(outboundSegment),
  },
})

/**
 * Encode the deterministic outbound segment key.
 * @param chatId - destination chat.
 * @param sessionId - source session.
 * @param sourceEventSeq - session event seq the segment derives from.
 * @param segmentIndex - zero-based index within the segmentation.
 * @returns the four-tuple key; identical inputs always encode identically.
 */
export function outboundSegmentId(
  chatId: FeishuChatId, sessionId: SessionIdString, sourceEventSeq: number, segmentIndex: number,
): OutboundSegmentId {
  return `${chatId}:${sessionId}:${sourceEventSeq}:${segmentIndex}` as OutboundSegmentId
}
